from shop.models.products.product import Product
from shop.models.products.product_photo import ProductPhoto
from shop.models.products.smartphone import Smartphone
from shop.models.products.tablet import Tablet
from shop.models.products.smartphone_accessory import SmartphoneAccessory
from shop.models.products.tablet_accessory import TabletAccessory
from shop.models.products.notebook import Notebook
from shop.models.products.monitor import Monitor
from shop.models.products.system_unit import SystemUnit
from shop.models.products.monoblock import Monoblock
from shop.models.products.product_rating import ProductRating
